[
  {
    "name":"Text",
    "props":{
      "style":{
        {
          "type":"string",
          "title":"布局类型",
          "default":"relative",
        },
        "lineHeight":{
          "type":"measurement",
          "title":"高度",
          "default":1,
        },
        "borderColor":{
          "type":'color',
          "title":"边框颜色",
          "default":"undefined"
        },
        "borderWidth":{
          "type":'int',
          "name":"边框宽度",
          "default":undefined
        },
        "borderTopWidth":{
          "type":'int',
          "name":"上边框宽度",
          "default":"undefined"
        },
        "borderTopColor":{
          "type":'color',
          "name":"上边框颜色",
          "default":"undefined"
        },
        "borderBottomWidth":{
          "type":'int',
          "name":"下边框宽度",
          "default":"undefined"
        },
        "borderBottomColor":{
          "type":'string',
          "name":"下边框颜色",
          "default":undefined
        },
        "borderRightWidth":{
          "type":'int',
          "name":"右边框宽度",
          "default":undefined
        },
        "borderRightColor":{
          "type":'color',
          "name":"右边框颜色",
          "default":undefined
        },
        "borderLeftWidth":{
          "type":'int',
          "name":"左边框宽度",
          "default":undefined
        },
        "borderLeftColor":{
          "type":'color',
          "name":"左边框颜色",
          "default":undefined
        },
        "marginTop":{
          "type":"measurement",
          "name":"上边距",
          "default":0,
        },
        "marginBottom":{
          "type":"measurement",
          "name":"下边距",
          "default":0,
        },
        "marginRight":{
          "type":"measurement",
          "title":"右边距",
          "default":0,
        },
        "marginLeft":{
          "type":"measurement",
          "title":"左边距",
          "default":0,
        },
        "fontSize":{
          "type":"measurement",
          "title":"字体大小",
          "default":1,
        },
        "color":{
          "type":'color',
          "name":"字体颜色",
          "default":'black'
        }
      },
      "text":{
        "type":'string',
        "name":"字体颜色",
        "default":'文本框'
      }
    }
  }

]
