module.exports = {
  object:{
  "name":"View",
  "props":{
    style:[
        {
          "name":"position",
          "value":"relative",
          "constant":true
        },
        {
          "name":"flexDirection",
          "value":'column',
          'constant':true
        },
        {
          "name":"height",
          "value":"componentHeight",
          "constant":true
        },
        {
          "name":"width",
          "value":"componentWidth",
          "constant":true
        }
    ]
  },//<View style={{flex:1}}/>
  "children":[
    {
      "name":"Image",
      "props":{
        "style":[
          {
            "name":"position",
            "value":"absolute",
            "constant":true
          },
          {
            "name":"zIndex",
            "value":1,
            "constant":true
          },
          {
            "name":"height",
            "value":"componentHeight",
            "constant":true
          },
          {
            "name":"width",
            "value":"componentWidth",
            "constant":true
          }
        ],
        "src":{
          "value":"../img/headpage_pic_syjh.png",
          "constant":true,
          "type":"image",
          "componentPropName":"backgroundImage"
        }
      }
    },
    {
      "name":"Text",
      "props":{
        "style":[
          {
            "name":"lineHeight",
            "value":2.7,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"zIndex",
            "value":2,
            "constant":true
          },
          {
            "name":"marginTop",
            "value":3,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"marginLeft",
            "value":3,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"marginBottom",
            "value":0,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"fontSize",
            "value":2.7,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"color",
            "value":'#111',
            "constant":false,
            "componentPropName":"titleColor"
          }
        ],
        "text":{
          "value":"ddd",
          "constant":false,
          "componentPropName":"title"
        }
      }
    },
    {
      "name":"Text",
      "props":{
        "style":[
          {
            "name":"lineHeight",
            "value":2.7,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"zIndex",
            "value":3,
            "constant":true
          },
          {
            "name":"marginTop",
            "value":3,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"marginLeft",
            "value":3,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"fontSize",
            "value":2.7,
            "type":"measurement",
            "constant":true
          },
          {
            "name":"color",
            "value":'#111',
            "constant":false,
            "componentPropName":"titleColor"
          }
        ],
        "text":{
          "value":"测试中文",
          "constant":false,
          "componentPropName":"title"
        }
      }
    },
  ]
}
}
