export default
{
  "dataTypeMapping":{
    "enum":{
      "position":{
        "params":["relative","absolute"],
        "paramsType":"string"
      },
      "alignItems":{
        "paramsType":"string",
        "params":["flex-start","flex-end","center","stretch"]
      },
      "justifyContent":{
        "paramsType":"string",
        "params":["flex-start","flex-end","center","space-between","space-around"]
      },
      "flexDirection":{
        "paramsType":"string",
        "params":["row","column"]
      },
      "pressType":{
        "paramsType":"string",
        "params":["finance_showcase","none"]
      },
      "fontWeight":{
        "paramsType":"string",
        "params":['normal', 'bold', '100', '200', '300', '400', '500', '600', '700', '800', '900']
      }
    },
  },
  "dataTypeName":{
    "position":"布局类型",
    "height":"高度",
    "width":"宽度",
    "borderColor":"边框颜色",
    "borderWidth":"边框宽度",
    "borderTopWidth":"上边框宽度",
    "borderTopColor":"上边框颜色",
    "borderBottomWidth":"下边框宽度",
    "borderBottomColor":"下边框颜色",
    "borderRightWidth":"右边框宽度",
    "borderRightColor":"右边框颜色",
    "borderLeftWidth":"左边框宽度",
    "borderLeftColor":"左边框颜色",
    "marginTop":"上边距",
    "marginBottom":"下边距",
    "marginRight":"右边距",
    "marginLeft":"左边距",
    "alignItems":"alignItems",
    "justifyContent":"justifyContent",
    "backgroundColor":"背景色",
    "top":"top",
    "bottom":"bottom",
    "right":"right",
    "left":"left",
    "src":"图片链接",
    "fontWeight":"字体粗细"
  }
}
