export default {
  "name":"TouchableOpacity",
  "props":{
    "style":[
      {
        "name":"position",
        "type":"enum",
        "default":"relative",
      },
      {
        "name":"height",
        "type":"measurement",
        "default":3,
      },
      {
        "name":"width",
        "type":"measurement",
        "default":3,
      },
      {
        "name":"marginTop",
        "type":"measurement",
        "default":0,
      },
      {
        "name":"marginBottom",
        "type":"measurement",
        "default":0,
      },
      {
        "name":"marginRight",
        "type":"measurement",
        "default":0,
      },
      {
        "name":"marginLeft",
        "type":"measurement",
        "default":0,
      },
      {
        "name":"alignItems",
        "type":"enum",
        "default":"center",
      },
      {
        "name":"justifyContent",
        "type":"enum",
        "default":"center",
      },
      {
        "name":"backgroundColor",
        "type":"string",
        "default":undefined
      },
      {
        "name":"flexDirection",
        "type":"enum",
        "default":"row"
      }
    ],
    "pressType":{
      "type":'enum',
      "name":"pressType",
      "default":undefined
    }
  }
}
